history: another attempta

diff --git a/.github/workflows/nightly.yaml b/.github/workflows/nightly.yaml
--- a/.github/workflows/nightly.yaml
+++ b/.github/workflows/nightly.yaml
@@ -273,6 +273,7 @@ jobs:
                   allure_report: allure-report
                   gh_pages: gh-pages
                   allure_history: allure-history
+                  subfolder: allure-report
                   keep_reports: 30
 
             - name: Upload Allure Report
@@ -283,11 +284,21 @@ jobs:
                   retention-days: 30
                   if-no-files-found: warn
 
+            - name: Prepare Pages deploy
+              if: github.event_name != 'pull_request' && github.event_name != 'merge_group'
+              run: |
+                  cp -r allure-report/* allure-history/
+                  echo "-------------- allure-history top level------------"
+                  ls -la allure-history/
+                  echo "------------ allure-history/last-history ------------"
+                  ls -la allure-history/last-history/ 2>/dev/null || echo "missing"
+                  echo "------------ allure-history/history ------------"
+                  ls -la allure-history/history/ 2>/dev/null || echo "missing"
             - name: Deploy to GitHub Pages
               if: github.event_name != 'pull_request' && github.event_name != 'merge_group'
               uses: peaceiris/actions-gh-pages@v4
               with:
                   github_token: ${{ secrets.GITHUB_TOKEN }}
-                  publish_dir: allure-report
+                  publish_dir: allure-history
                   destination_dir: allure-report
                   keep_files: true
